String buildVersion
String buildName='spring-petclinic-aws'
String ciBucketName='xchu-jenkins-artifacts-build-us-east-1'
String rcBucketName='xchu-jenkins-artifacts-rc-us-east-1'
String awsCred='lab-aws'
String defaultRegion='us-east-1'

pipeline{
    agent any
    parameters {
        string(name: 'version', description: 'Version to Deploy')
        string(name: 'environment', description: 'Environment to Deploy to')
        choice(name: 'region', choices: ["${defaultRegion}",'ca-central-1'], description: 'Deployment Region')
    }
    stages {
        stage('Set up Deployment variables.'){
            steps{
                script{
                    buildVersion = params.version
                    environment = params.environment
                    region = params.region
                    stackName = "${buildName}-${environment}"
                }
            }
        }

        stage('Deploy Stack'){
            steps{
                dir('cdk') {
                    withAWS(credentials:"${awsCred}", region:"${region}"){
                        // env var of jenkins pipeline can't be used within script block, hence has to be passed as env
                        withEnv(["CDK_DEFAULT_ACCOUNT=${env.AWS_ACCOUNT_ID}", "CDK_DEFAULT_REGION=${region}"]) {
                            script {
                                sh 'npm install' // install dependencies in package.json
                                output = sh(script: "cdk deploy --require-approval never --context imageTag=${buildVersion} \
                                    --context ecrRepo=${buildName} --context stackName=${stackName}", returnStdout: true).trim()
                            }
                        }
                    }
                }
            }
        }

        stage('Report URL'){
            steps{
                script {
                    def albDnsName = output.readLines().findAll { it.trim().startsWith('EcsStack.ALBDnsName') }.collect { it.split('=')[1].trim() }[0]
                    echo "Petclinic URL is http://${albDnsName}"
                }
            }
        }
    }  
}